### PR TITLE
Revert smapp changes

### PR DESCRIPTION
**Pull request by natewalck**
This reverts the SMAppService changes until we can fully test all the edge cases and Apple perhaps makes SMAppService an actual functional way of managing LaunchAgents.

### CODE REVIEW

**Comment by natewalck** [comment]
I can't seem to re-break my machine to test, if someone doesn't mind doing the tests we did before in a VM, that would be super helpful.

https://github.com/macadmins/nudge/releases/tag/v1.1.13.81506

I think we have 3 cases to test:

1. Fresh Machine
2. Machine with 1.1.11 => 1.1.13
3. Machine that did 1.1.11 => 1.1.12 and is in a bad state (BTM error is present in log)
    - Update to the new build, see if it loads or still throws BTM errors

**Comment by erikng** [comment]
I wonder if there is a way to just return the code vs deleting it. I still don't understand why Apple is using this logic automatically when it's not supposed to trigger unless explicitly set

**Comment by natewalck** [comment]
What would the advantage of returning the code be vs removing it for now? It would be trivial to add back later.

**Comment by erikng** [comment]
I more so just don't understand the behavior that's happening.

**Comment by kevinmcox** [comment]
In my first test going 1.1.11 --> 1.1.12 --> 1.1.13.81506 (gutted SMAS), it doesn’t fix the problem. The legacy LA still refuses to load. Even after a reboots and even opening Nudge manually.

So it looks like going with either of the two 1.1.13 pre-releases (updated SMAS or gutted SMAS) will still require admins to take some manual action to remediate. (Since it sounds like us deciding to do it for them by running `sfltool resetbtm` isn’t a good option due to side effects.)

So admins who have already deployed 1.1.12 and are experiencing this problem will have to handle running `sfltool resetbtm`, with side effects, on their own; or as JC mentioned yesterday, fully uninstall Nudge 1.1.12, agents, etc. then reinstall 1.1.13 plus agents.

**Comment by natewalck** [comment]
Given this doesn't actually fix anything and would perhaps make it even more confusing adding/removing the pref, Let's kill this PR.

**Pull request closed without merging**
