### PR TITLE
coerce string for requiredInstallationDate into Date

### PR DESCRIPTION
**Pull request by erikng**
So I want to put this up and have a discussion. This would allow you to pass a String for the `requiredInstallationDate` key.

What this basically solves is Jamf JSON Schema, allowing someone to finish that and maybe help jamf users. It appears that unless people sign their profiles before pushing them, jamf breaks them.

This is a workaround to workaround multiple bad behaviors that jamf has, so I don't want to necessarily merge it. I'm looking for feedback both from jamf users and non-jamf users.

Food for thought: the JSON takes a String for this key, because JSON doesn't support `data`. Swift can handle this natively for us though and converts it. NSUserDefaults though has to have this coerce logic, so it's not as elegant.

### CODE REVIEW

**Comment by erikng** [comment]
Maybe a thumbs up or down on this comment if you want it to be merged or not. If you have more to say, please comment.

**Comment by grahampugh** [comment]
It would be very useful for us as we have 35 Jamf instances and you can't copy signed profiles via the API, but you can with a working unsigned custom profile.

So 👍 for the merge.

**Comment by smithjw** [comment]
I think the benefits outweigh the risks/burden here as it drastically increases the likelyhood of Admins utilising Nudge in their environment if they are able to configure it via a Jamf Custom Schema. I'm happy to write/finish/contribute to this scheme if this change is merged in

**Comment by erikng** [comment]
After talking this through with @chefaustin I've determined that I'm going to merge this.

**Comment by grahampugh** [comment]
Nice, thanks!

**Comment by MrTreger** [comment]
Defo would like to give this a try over config profiles!

**Pull request merged**
