### PR TITLE
Grace Periods for newly provisioned machines

### PR DESCRIPTION
**Pull request by erikng**
Addresses: https://github.com/macadmins/nudge/issues/328

```json
  "userExperience": {
    "allowGracePeriods": false,
    "gracePeriodInstallDelay": 23,
    "gracePeriodLaunchDelay": 1,
    "gracePeriodPath": "/private/var/db/.AppleSetupDone"
}
```
- ~~Once the age of `gracePeriodPath` is greater than both the `gracePeriodInstallDelay` and `gracePeriodLaunchDelay` the `requiredInstallationDate` is going to revert to the original date in the profile/json. From a user experience perspective, nothing will change as in both cases, the user is now passed the original requiredInstallationDate or new requiredInstallationDate.~~
  - ~~I'm not too worried about this~~

- ~~Each time nudge runs during the `gracePeriodInstallDelay`, the `requiredInstallationDate` is going to keep moving for the user. This is because `allowButtons` is set to `false` only when the user is passed the `allowedDeferrals` count or passed the `requiredInstallationDate`.~~
  - ~~This is hugely problematic, and the only way I can think to solve this issue is to start adding the `requiredInstallationDate` to the user's preference file and using it for this logic. I will then have to remove this key if it exists post this behavior.~~
  
See https://github.com/macadmins/nudge/pull/330#issuecomment-1054654895 for an updated set of behaviors and thoughts

### CODE REVIEW

**Comment by erikng** [comment]
So I've redone the logic entirely and came away with the following conclusion - it doesn't matter if you are before or after the `requiredInstallationDate`

- if you are either passed `requiredInstallationDate` OR (`gracePeriodInstallDelay` + `gracePeriodLaunchDelay`) > the number of hours remaining in a nudge event
  - if you are under the `gracePeriodLaunchDelay`, nudge exits out
  - If you are over the `gracePeriodLaunchDelay`, your `requiredInstallationDate` is the created date of `gracePeriodPath` + (`gracePeriodInstallDelay` + `gracePeriodLaunchDelay` in hours). By default that gives you 24 hours to install the required update, which is within the `imminentWindow` by default, giving the user a way to exit out.

I think rather than solving the various amounts of edge cases, I would rather document the following for the admin
- the total grace period is `gracePeriodInstallDelay` + `gracePeriodLaunchDelay`, which defaults to 24 (23 + 1)
- the `imminentWindow` defaults to 24, and you should test the user experience should you you increase the gracePeriodDelay values to something that's higher as Nudge's user experience may change.
  - Example: If you were to set it to the values to 1 and 71 respectively, you Nudge would show the `approachingWindow` logic so long as the default was kept of `72`

**Review by rorymurdock — APPROVED** [review]
LGTM

Note:
Would run into multi user issues if it's lab or something.

**Comment by rorymurdock** [comment]
As mentioned, this code is prime for Unit testing

**Comment by erikng** [comment]
> As mentioned, this code is prime for Unit testing

I hate you. It's done.

**Pull request merged**
