### PR TITLE
French fixes

### PR DESCRIPTION
**Pull request by ygini**
Fixing the french locale with proper capitalization for french language and other typos.

### CODE REVIEW

**Comment by erikng** [comment]
Is it common in French to do

something (space) colon?

the French localization won't match any of the other styles if you add those spaces. 

Everything else is

something:
Whereas this PR now does
something :

**Comment by ygini** [comment]
Yes, that's actually a syntax rule in french: all punctuation with two parts (:;?!) require an insecable space before

**Comment by erikng** [comment]
Got it. There looks to be a git conflict. Can you look into that?

**Comment by erikng** [comment]
I fixed the conflicts. Thanks for the PR.

**Pull request merged**
