### PR TITLE
Layout cleanup

### PR DESCRIPTION
**Pull request by bartreardon**
Addresses: https://github.com/macadmins/nudge/issues/241

This PR covers a lot of changes but the intent is to clean up the code used for layout and make appearance consistent between macOS 11 and macOS 12.

The bulk of the changes remove (as much as possible) any direct references to individual view width and height declarations on the main body of the code. The window size is defined by two constants declared in `main` and everything else is positioned accordingly by inheriting the parent window size (also of general note, when defining a window height and using `.windowStyle(.hiddenTitleBar)` the title bar is hidden but the space it would take up is still there. So a height of `450` is actually `450+28`. Thought that was interesting)

Also I noticed a bunch of duplicated code for common views between standard and simple modes so I've separated them out so they can be re-used elsewhere.

`Nudge.xcodeproj/project.pbxproj` somehow made it in to the PR - I though I had removed that from the commits but somehow ~palpatine returned~ it snuck in there. hope that doesn't mess up the PR but can always be overwritten.

there's still `.padding(.leading, -200.0)` in `primaryQuitButton.swift` - I can see the effect but not determined what it's doing (moving it all off screen?) - it should be fine for now but will look at that at some point later.

not all modes have been fully tested at this stage - everything should still operate though and at worst - please yell at me if something look _really_ off

### CODE REVIEW

**Comment by erikng** [comment]
I'll try and play with this tomorrow but quick look and it's pretty good (although appears incomplete?).

I'M very glad I moved to ObservableObject or some of your changes would have been incredibly difficult to achieve. I too had wanted to move the buttons to their own Swift file so that is a welcome change.

**Comment by erikng** [comment]
Also yes that 28px titlebar stuff is annoyingly difficult to understand. Since Apple would never approve nudge in the App Store it does not follow HIG and consequently SwiftUI was never designed to do something like this.

**Comment by bartreardon** [comment]
> (although appears incomplete?)

Oh? - where about do you see that? it's only hit 9am here so plenty of time to fiddle with stuff if there's something obviously amiss (I'll admit I did some quick cleanup and PR before coffee so....)

**Comment by erikng** [comment]
You have a few lines of `//`

**Comment by bartreardon** [comment]
ah - ok - yeah I can clean those up.

the cleanup this morning was to ensure that it compiled cleanly and it still displayed correctly for testing in both standard and simple modes. There's still a little work to be done moving some of the logic around but hopefully the direction I'm going is clear from what you see in the PR.

I'll just add that in the process I've done my best to ensure the adjusted layout looks the same as it did before but there will be some minor differences here and there. Hopefully those are acceptable for the greater good. shouldn't be noticeable unless you compare old screenshots to new with a discerning eye.

**Comment by erikng** [comment]
There were UI changes from 1.0 to 1.1 that were only visible in the same way (and I wasn't the biggest fan of them) so if it changes slightly again, NBD. The gains from this are worth it and the value here is quite high.

If you can clean up the Xcode project file and revert those changes + anything else you want to finish today, I'll look at it in the AM in Xcode and play around.

**Comment by bartreardon** [comment]
ok see how that goes - pulled upstream dev branch and merged in and seems to pass all checks now

**Comment by bartreardon** [comment]
ok - the specific lines in the project file...my git foo isn't up to snuff but it seems possible to ignore certain lines in a file. not sure how to manage that and switching between different teams. There are change that are needed since I added additional files to the project so I can't ignore the file wholesale. LMK how you'd like to proceed here. brute force way would be to merge, fix the project locally and commit your own team settings but that doesn't seem as elegant.

**Comment by erikng** [comment]
> ok - the specific lines in the project file...my git foo isn't up to snuff but it seems possible to ignore certain lines in a file. not sure how to manage that and switching between different teams. 

I don't think there is a good way to do this since the lines could change at any time and then you have a mismatch of the project. The only way I can think of is to change it back per PR, or do what you are saying and merge/then re-commit.

I don't like the idea of merge/re-committing, so I would ask for you to change them back outside of Xcode (say VSC or Atom). I would do it myself but don't have access to your forked repo.

**Comment by erikng** [comment]
There is definitely a bug with standardMode changing its height on the mainContentText/buttons and also a bug with how simpleMode looks. I've fixed a few other design things I didn't personally like.

**Comment by erikng** [comment]
There is a small bug with -debug-mode and the buttons not being passed. I don't know if this is an actual issue to worry about or just the way `ContentView()` is called. In the back of my head, I'm thinking that the `nudgeState` class is being created as two objects in memory, which would be a small issue, but if I'm wrong, then it means Nudge has broken with this PR.

Either way it can likely be fixed, just not sure how big of an issue exists.

**Comment by erikng** [comment]
Crisis adverted. Small issue :) After your refactoring of `PrimaryQuitButton()` the state was contained to each call, so it was in fact a memory issue, but not an issue of `nudgeState` memory. I moved the variable within PQB to the primary ObservableObject class and it immediately fixed the issue.

**Comment by bartreardon** [comment]
woot - I'll check out your changes and make some notes. 100% need to keep an eye on that project file. I think there's a way in git to tell it to ignore specific lines which might be useful, but probably not a big deal as it's only an issue if there are new views views/files being created. else I just need to remember to not commit the project file (or work out how to remove it from the commit - which I though I did but it was still there so 🤷‍♂️ )

all this to fix the positioning of the (?) icon 😜

**Comment by erikng** [comment]
Heh the one thing I learned about separating the SwiftUI files is you really have to use ObservableObject to reduce code calls and ensure the UI state is updated synchronously for all elements. 

I didn't do this because I was ignorant for v1.0 and then did a bunch of hacky things to work around it. Then when I wrote hello, it finally clicked for me.

Making everything separate is great for reducing repetition but has to be done methodically.

**Pull request merged**
