### PR TITLE
add acceptableApplicationBundleIDs feature

### PR DESCRIPTION
**Pull request by erikng**
A new key `acceptableApplicationBundleIDs` is now available.

```
  "optionalFeatures": {
    "acceptableApplicationBundleIDs": [
      "us.zoom.xos"
    ]
  },
```

### CODE REVIEW

**Comment by erikng** [comment]
Addresses: https://github.com/macadmins/nudge/issues/180

**Comment by dan-snelson** [comment]
@erikng One word: Sweetness!

Works precisely as advertised.

(What kind of a special headache would it be to log when the `acceptableApplicationBundleIDs` condition is met?)

**Comment by erikng** [comment]
It does actually

`2021-08-18 08:03:18.212022-0500 Nudge[1819:21838336] [user-interface] acceptableApplication (us.zoom.xos) is currently the frontmostApplication`

**Comment by dan-snelson** [comment]
Excellent; I'm not seeing any related entries on my single test machine.

(I _am_ redirecting Nudge's logging, FWIW.)

**Comment by erikng** [comment]
Those log events are a higher priority so they would only be set if you increased the log level. This is mainly due to wanting to keep the noise ratio down on what the logger writes to disk (and the health of SSD's).

**Pull request merged**
