### PR TITLE
Create SECURITY.md so I can notify a vulnerability in this repo

### PR DESCRIPTION
**Pull request by carlospolop**
Please, create a security policy in this repo so I can notify securely a vulnerability in this project

### CODE REVIEW

**Comment by erikng** [comment]
Are you suggesting there is a security issue in the project and the only way you will report it is by having some random markdown file?

**Comment by HowardGMac** [comment]
This definitely smells of mackerel or maybe blue fin....

**Comment by erikng** [comment]
I created my own security.md file. Looking forward to hearing from you.

**Comment by carlospolop** [comment]
I just send the email, thanks for creating the file @erikng

**Pull request closed without merging**
