### PR TITLE
Fix layout of the "Defer" date picker view

### PR DESCRIPTION
**Pull request by bartreardon**
Part 2 of fixing the issues raised in https://github.com/macadmins/nudge/issues/246

A little more work but brings the view declaration into line with how other views are defined with stronger reliance on letting SwiftUI do the layout for the most part

Before:
defer-before

After:
Screen Shot 2021-09-07 at 5 06 27 pm

### CODE REVIEW

**Comment by bartreardon** [comment]
tested on macOS 11 and 12

**Comment by erikng** [comment]
I had planned on fixing this but yay, now I don't have to. Thanks buddy! :)

**Comment by bartreardon** [comment]
ha - well was in the mood for it (and I might have ddid it in the last PR if I wasn't running a headache and realised where the change was needed)....anyway- pity that http image branch won't go away for whatever reason - revert, rebase, unmerge, exorcise, pull.....this is why people nuke and re-clone. :/

**Comment by erikng** [comment]
That's why I squashed this PR into a single commit. What I would suggest is destroying your development branch and then creating a new branch from my origin development branch. Should fix you up moving forward.

**Pull request merged**
